In [47]:
import numpy as np

arr_1d=np.array([1,2,3])
print(arr_1d)
print(type(arr_1d))
arr_2d=np.array([[1,2,3],[4,5,6]]) # cant incerase size of numpy array but can change the values
print(arr_2d)
print(arr_2d.dtype)
print(arr_2d.size)
print(arr_2d.ndim)
print(arr_2d.shape)
c=arr_1d[1:2]
print("c : ",c)
a=np.array([10,20,30,40,50])
a[3:5]=300
print('a',a)

[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
int32
6
2
(2, 3)
c :  [2]
a [ 10  20  30 300 300]


In [12]:
#Q1
import numpy as np
A=np.array([1,2,3,4,5])
print(A)
B=np.array([])
B=A
print("B : ",B)
for i in range(0,5):
    A[i]=A[i]+2
print(A)

for i in range(0,5):
    A[i]=A[i]*3
print(A)

for i in range(0,5):
    A[i]=A[i]/2
print(A)


[1 2 3 4 5]
B :  [1 2 3 4 5]
[3 4 5 6 7]
[ 9 12 15 18 21]
[ 4  6  7  9 10]


In [22]:
#Q2
import numpy as np
#a
arr = np.array([1,2,3,6,4,5]) # arr=arr[::-1] for reverse fo only 1d
arr=np.flip(arr)
print(arr)

#b
def most_frequent(arr):
    counts=np.bincount(arr) #counts the occurrences of each integer in the array and returns a frequency array
    most_frequent=counts.argmax()
    return most_frequent
       
x=np.array([1,2,3,4,5,1,2,1,1,1])
print('x:',x)
x_most_frequent=most_frequent(x)
print('In x most frequent element : ',x_most_frequent)
print('The indice of x most frequent element :')
idx=0
for i in x:
    if(i==x_most_frequent):
        print(idx)
    idx=idx+1

[5 4 6 3 2 1]
x: [1 2 3 4 5 1 2 1 1 1]
In x most frequent element :  1
The indice of x most frequent element :
0
5
7
8
9


In [38]:
#3
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print('given arr:\n',arr)

#a Access 1st row, 2nd column
a=arr[0,1]
print(a)

#b Access 3rd row, 1st column
b=arr[2,0]
print(b)

given arr:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
20
70


In [97]:
#4
import numpy as np
kanav=np.linspace(10,100,25)
print(kanav)
print('The dimension of array : ',your_name.ndim)
print('The shape of array : ',your_name.shape)
print('The total elements of array : ',your_name.size)
print('The dataype of each element in array : ',your_name.dtype)
print('The total bytes consumed by array : ',your_name.nbytes)
transpose_array=kanav.reshape(25, 1)
print(f"Transpose of the array using reshape():\n{transpose_array}")
transpose_using_T=kanav.T
print(f"Transpose of the array using T attribute:\n{transpose_using_T}")

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
The dimension of array :  1
The shape of array :  (25,)
The total elements of array :  25
The dataype of each element in array :  float64
The total bytes consumed by array :  200
Transpose of the array using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose of the array using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [91]:
#5
import numpy as np
ucs420_kanav=np.array([
                       [10,20,30,40],
                       [50,60,70,80],
                       [90, 15, 20, 35]
])
flat_array=ucs420_kanav.flatten() # convet to 1D array

mean_val=np.mean(flat_array)
median_val=np.median(flat_array)
max_val=np.max(flat_array)
min_val=np.min(flat_array)
unique_elements=np.unique(flat_array)

print("Mean: ",mean_val)
print("Median: ",median_val)
print("Max: ",max_val)
print("Min: ",min_val)
print("Unique Elements: ",unique_elements)

reshaped_ucs420_kanav=np.reshape(ucs420_kanav,(4,3))
print('4 rows 3 columns')
print(reshaped_ucs420_kanav)

resized_ucs420_kanav=np.resize(ucs420_kanav,(2,3))

print('2 rows 3 columns')
print(resized_ucs420_kanav)

Mean:  43.333333333333336
Median:  37.5
Max:  90
Min:  10
Unique Elements:  [10 15 20 30 35 40 50 60 70 80 90]
4 rows 3 columns
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
2 rows 3 columns
[[10 20 30]
 [40 50 60]]
